language: node_js

node_js:
  - '10.13.0'

cache:
  directories:
    - 'node_modules'

install:
  - yarn install

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script: yarn build
    - stage: deploy
      script:
        - yarn vsce -p $VSCODE_SECRET
